[package]
name = "cs_call_rst"
version = "0.1.0"
authors = ["Ben Chatelain <ben@octop.ad>"]
rust-version = "1.59"
edition = "2021"

[lib]
crate-type = ["dylib"]
name = "cs_call_rst"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
